# At fist stop ROS Master if working on host

# Quick Start for mapping: (at fist stop ROS Master if working on host)
# $ docker-compose -f compose.rosbot.hardware.yaml -f compose.rosbot.mapping.yaml -f compose.rosbot.lan.yaml up

# Quick Start for localization:
# $ docker-compose -f compose.rosbot.control.yaml -f compose.rosbot.hardware.yaml -f compose.rosbot.localization.yaml -f compose.rosbot.lan.yaml up

version: '2.3'

services:

  rplidar:
    image: husarion/rplidar:galactic
    container_name: rplidar-galactic
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0
    command: >
      ros2 launch sllidar_ros2 sllidar_launch.py
        serial_baudrate:=${RPLIDAR_BAUDRATE}

  bridge:
    image: husarion/ros:galactic-ros1-bridge
    container_name: ros-bridge
    restart: unless-stopped
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
    command: >
      ros2 run ros1_bridge dynamic_bridge

  ros-master:
    image: ros:noetic-ros-core
    container_name: ros-master
    restart: unless-stopped
    command: stdbuf -o L roscore

  rosbot:
    image: husarion/rosbot:noetic
    container_name: rosbot-hardware-noetic
    restart: unless-stopped
    devices:
      - ${SERIAL_PORT}
    environment:
      - SERIAL_PORT
      - ROS_MASTER_URI=http://ros-master:11311
    command: >
      roslaunch --wait rosbot_bringup rosbot_docker.launch
