# can be optimized

FROM ros:foxy

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY . ./

RUN sudo apt update && \
    source /opt/ros/foxy/setup.bash && \
    echo "================== ROS FOXY INSTALL (controller) ======================" && \
    sudo apt install -y ros-foxy-rqt* ros-foxy-joint-state-publisher && \
    echo "================== GIT CLONE (controller) ======================" && \
    mkdir -p ros2_ws/src && \
    cd ros2_ws/src && \
    git clone -b foxy-devel https://github.com/ROBOTIS-GIT/DynamixelSDK.git && \
    git clone -b ros2 https://github.com/ROBOTIS-GIT/dynamixel-workbench.git && \
    git clone -b foxy-devel https://github.com/ROBOTIS-GIT/open_manipulator.git && \
    git clone -b ros2 https://github.com/ROBOTIS-GIT/open_manipulator_msgs.git && \
    git clone -b ros2 https://github.com/ROBOTIS-GIT/open_manipulator_dependencies.git && \
    git clone -b ros2 https://github.com/ROBOTIS-GIT/robotis_manipulator.git && \
    cd .. && \
    echo "================== COLCON BUILD (controller) ======================" && \
    colcon build && \
    source /opt/ros/foxy/setup.bash && \
    echo "source /app/ros2_ws/install/setup.bash">>~/.bashrc

COPY docker_stuff/ros_entrypoint.sh /

ENTRYPOINT [ "/ros_entrypoint.sh" ]

CMD ["bash"]